// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    restTables,
    productTypesTable,
    taxes,
    productsClass,
    orders,
    orderLines,
    payments,
  ];
  late final Shape0 restTables = Shape0(
    source: i0.VersionedTable(
      entityName: 'rest_tables',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 productTypesTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'product_types_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_5, _column_6, _column_7],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 taxes = Shape2(
    source: i0.VersionedTable(
      entityName: 'taxes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_5, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 productsClass = Shape3(
    source: i0.VersionedTable(
      entityName: 'products_class',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_9,
        _column_6,
        _column_7,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 orders = Shape4(
    source: i0.VersionedTable(
      entityName: 'orders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_4,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 orderLines = Shape5(
    source: i0.VersionedTable(
      entityName: 'order_lines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_5,
        _column_19,
        _column_20,
        _column_14,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 payments = Shape6(
    source: i0.VersionedTable(
      entityName: 'payments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_25, _column_26, _column_27, _column_24],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get top =>
      columnsByName['top']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get left =>
      columnsByName['left']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get number =>
      columnsByName['number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get state =>
      columnsByName['state']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<double> _column_1(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'top',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_2(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'left',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'number',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rate =>
      columnsByName['rate']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rate',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get color =>
      columnsByName['color']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get table =>
      columnsByName['table']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES product_types_table (id)',
      ),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'table',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES taxes (id)',
      ),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get closedAt =>
      columnsByName['closed_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get totalPrice =>
      columnsByName['total_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get payedPrice =>
      columnsByName['payed_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalTaxes =>
      columnsByName['total_taxes']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalPriceWithTaxes =>
      columnsByName['total_price_with_taxes']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get state =>
      columnsByName['state']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get taxes =>
      columnsByName['taxes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<DateTime> _column_12(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_13(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'closed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'payed_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_16(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_taxes',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_17(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'total_price_with_taxes',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'taxes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES rest_tables (id)',
      ),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productName =>
      columnsByName['product_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get currentPrice =>
      columnsByName['current_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get totalPrice =>
      columnsByName['total_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get taxRate =>
      columnsByName['tax_rate']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get taxPrice =>
      columnsByName['tax_price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_20(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'current_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_21(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tax_rate',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tax_price',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES orders (id)',
      ),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get paymentMethod =>
      columnsByName['payment_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get payedAmount =>
      columnsByName['payed_amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get paymentDateTime =>
      columnsByName['payment_date_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payment_method',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<double> _column_26(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'payed_amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<DateTime> _column_27(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'payment_date_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
